apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthflow-backend
  labels:
    app: healthflow-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: healthflow-backend
  template:
    metadata:
      labels:
        app: healthflow-backend
    spec:
      containers:
        - name: backend
          image: asia-south1-docker.pkg.dev/project-de920623-03c7-48d1-864/healthflow-repo/backend:latest
          ports:
            - containerPort: 8080

          readinessProbe:
            httpGet:
              path: /api/v1/auth/health
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6

          livenessProbe:
            httpGet:
              path: /api/v1/auth/health
              port: 8080
            initialDelaySeconds: 150
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 6

          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: healthflow-secrets
                  key: DATABASE_URL
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: healthflow-secrets
                  key: DATABASE_USERNAME
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: healthflow-secrets
                  key: DATABASE_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: healthflow-secrets
                  key: JWT_SECRET
            - name: CORS_ALLOWED_ORIGINS
              value: "*"
            - name: PORT
              value: "8080"

          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  selector:
    app: healthflow-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
